services:
  # Base de Dades
  db:
    image: postgres:15-alpine
    container_name: receptes_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # API Receptes
  api:
    build: .
    container_name: receptes_api
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      # El host és el nom del servei de la base de dades: 'db'
      - DATABASE_URL=postgresql+psycopg://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}

volumes:
  postgres_data: